"""add_performed_by_to_labreport

Revision ID: 89b2c60c71c7
Revises: e8f1c7ab2190
Create Date: 2026-03-20 20:52:56.147648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89b2c60c71c7'
down_revision = 'e8f1c7ab2190'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lab_reports', sa.Column('performed_by', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lab_reports', 'performed_by')
    # ### end Alembic commands ###


